/**
 * 
 */
package no.ovitas.compass2.config.settings;

/**
 * @class PluginType
 * @project compass2-core
 * @author Milan Gyalai (gyalai@mail.thot-soft.com) 
 * @version 
 * @date 2010.09.09.
 * 
 */
public enum PluginType {
	FULL_TEXT_SEARCH_MAIN_PLUGIN, FULL_TEXT_SEARCH_PLUGIN, CONTENT_HANDLER_PLUGIN, INDEXER_PLUGIN, KNOWLEDGE_BASE_MAIN_PLUGIN, KNOWLEDGE_BASE_PLUGIN, IMPORT_MAIN_PLUGIN, LANGUAGE_TOOL_MAIN_PLUGIN, LANGUAGE_TOOL_PLUGIN, IMPORT_PLUGIN, CONTENT_HANDLER_MAIN_PLUGIN, SUGGESTION_PROVIDER_MAIN_PLUGIN, SUGGESTION_PROVIDER, QUERY_BUILDER_PLUGIN, TOPIC_NAME_INDEXER_PLUGIN, REFERRAL_PLUGIN, REFERRAL_MAIN_PLUGIN

}
